name: Lobbysystem
version: '1.0-SNAPSHOT'
main: de.rubymc.lobbysystem.Main
api-version: 1.16
authors: [ Waischbrot ]
description: Lobbysystem ^^
website: https://rubymc.de

softdepend: [PlaceholderAPI]

commands:
  lobby:
    permission: lobby.command
    aliases: [ lb ]
    description: Lobbysystems main command
