name: Lobbysystem
version: '${project.version}'
main: de.rubymc.lobbysystem.Main
api-version: 1.16
authors: [ Waischbrot ]
description: Lobbysystem ^^
website: https://rubymc.de

softdepend: [PlaceholderAPI, SpigotAPI]

commands:
  build:
  removewarp:
    aliases: [ delwarp, remwarp]
  rubine:
    aliases: [coins, rubys]
  setspawn:
  spawn:
  setwarp:
    aliases: [createwarp]
  warp:
